In [94]:
import random  
import numpy as np
import pandas as pd

class Chinese_poker:
    def __init__(self, total_num_of_cards, num_ofcards_per_person, num_of_players):
        
        '''
        total_num_of_cards     : total number of poker cards.
        num_ofcards_per_person : number of cards per person
        num_of_players         : number of players.
        pot_card               : 彩金
        self.hand_cards      : 玩家手上的牌
        card_list              : [1 ~ 52] or [1 ~ 52+13].

        '''

        self.total_num_of_cards     = int(total_num_of_cards)
        self.num_ofcards_per_person = int(num_ofcards_per_person)
        self.num_of_players         = int(num_of_players)
        self.pot_card               = None
        self.hand_cards             = None
        self.ranks_index            = []
        self.suits_index            = []
        
        if self.total_num_of_cards % 13 == 0:
            self.card_list  = [i for i in range(1, 1 + self.total_num_of_cards)]
        else:
            print('Error! Incorrect number of cards!')
    
    def shuffle(self, pot=None):

        if pot == None:
            random.shuffle(self.card_list)                 # 洗牌
        elif pot == 'choose':
            random.shuffle(self.card_list)                 # 洗牌
            self.pot_card = random.choice(self.card_list)  # 選出彩金鋪克牌
        elif pot == 'take':
            random.shuffle(self.card_list)                 # 洗牌
            self.pot_card = random.choice(self.card_list)  # 選出彩金鋪克牌
            self.card_list.remove(self.pot_card)           # 且將彩金鋪克牌「抽出」
        else:
            print('pot only equal string choose or take')

    def dealing_cards(self, pot=None):
        '''
        pot = "None, choose, take" only.
        '''
        num_of_players = self.num_of_players
        cards_per      = self.num_ofcards_per_person
        a              = []

        self.shuffle(pot)

        if self.num_of_players * self.num_ofcards_per_person > len(self.card_list):
            print('Error! Incorrect number of cards!')
        else:
            for i in range(self.num_of_players):
                a.append(self.card_list[0 + i * cards_per: cards_per * (i+1)])
            # print(a)
            self.hand_cards= np.array(a)
            # print(self.hand_cards)
            self.hand_cards.sort()                        # 將牌由小到大排列。


    def analysis_cards(self):
        '''
        find ranks numbers.
        鐵支, 三條, 對子.
        '''
        ranks = self.hand_cards % 13

        for i in range(self.num_of_players):
            self.ranks_index.append([])
            for j in range(0, 13):
                self.ranks_index[i].append(j)
                self.ranks_index[i].append(list(ranks[i]).count(j))

        '''
        找出花色
        同花順, 同花.
        '''
        suits = self.hand_cards // 13

        for i in range(self.num_of_players):
            self.suits_index.append([])
            # [1, 2, 3, 4] = ['♠', '♦', '♥', '♣']
            for j in range(1, 5):
                self.suits_index[i].append(j)
                self.suits_index[i].append(list(suits[i]).count(j))

    def straight_flush(self):
        print(self.suits_index)
        for i in range(self.num_of_players):
            for j in range(1,8,2):
                if self.suits_index[i][j] > 4:
                    print(f'player{i+1}: {self.suits_index[i][j-1]}')


C = Chinese_poker(52, 13, 4)
C.dealing_cards(pot=None)
C.analysis_cards()
C.straight_flush()


[[1, 4, 2, 3, 3, 3, 4, 0], [1, 4, 2, 3, 3, 1, 4, 0], [1, 2, 2, 5, 3, 2, 4, 1], [1, 3, 2, 2, 3, 7, 4, 0]]
player3: 2
player4: 3


In [87]:
a = [[43, 41, 22, 39, 13, 50, 18, 34, 45, 35, 46, 2, 31], 
     [37, 27, 4, 1, 14, 23, 38, 8, 28, 40, 5, 52, 33], 
     [25, 20, 29, 36, 6, 12, 21, 24, 9, 7, 47, 48, 44], 
     [49, 3, 11, 10, 19, 15, 26, 51, 17, 30, 42, 32, 16]
    ]
a = np.array(a)

In [113]:
def analysis_cards():
    '''
    find ranks numbers.
    鐵支, 三條, 對子.
    '''
    ranks = a % 13
    ranks_index = []

    for i in range(4):
        ranks_index.append([])
        for j in range(0, 13):
            ranks_index[i].append(j)
            ranks_index[i].append(list(ranks[i]).count(j))

    '''
    找出花色
    同花順, 同花.
    '''
    suits = a // 13
    suits_index = []

    for i in range(4):
        suits_index.append([])
        # [1, 2, 3, 4] = ['♠', '♦', '♥', '♣']
        for j in range(1, 5):
            suits_index[i].append(j)
            suits_index[i].append(list(suits[i]).count(j))
    return ranks_index, suits_index

ranks_index, suits_index = analysis_cards()
# print(ranks_index, '\n', '\n',suits_index)
PD_ranks_index = pd.DataFrame(np.array(ranks_index), 
                    columns = ['K', 'num', 'A', 'num', '2', 'num', '3', 'num', '4', 'num', '5', 
                               'num', '6', 'num', '7', 'num', '8', 'num', '9', 'num', 
                               '10', 'num', 'J', 'num', 'Q', 'num'],
                    index = ['Player1', 'Player2', 'Player3', 'Player4'])

PD_suits_index = pd.DataFrame(np.array(suits_index), 
                    columns = ['♠', 'num', '♦', 'num', '♥', 'num', '♣', 'num'],
                    index = ['Player1', 'Player2', 'Player3', 'Player4'])
print(PD_ranks_index.T)

print(PD_suits_index)

     Player1  Player2  Player3  Player4
K          0        0        0        0
num        2        1        0        1
A          1        1        1        1
num        0        4        0        0
2          2        2        2        2
num        2        1        0        1
3          3        3        3        3
num        0        0        1        3
4          4        4        4        4
num        1        1        0        2
5          5        5        5        5
num        2        1        1        0
6          6        6        6        6
num        1        0        1        2
7          7        7        7        7
num        1        1        2        0
8          8        8        8        8
num        1        1        2        0
9          9        9        9        9
num        2        0        2        0
10        10       10       10       10
num        0        1        1        2
J         11       11       11       11
num        1        1        1        1


In [108]:
def straight_flush():

    for i in range(4):
        for j in range(1,8,2):
            if suits_index[i][j] > 4:
                print(f'player{i+1}: {suits_index[i][j-1]}')
straight_flush()

player1: 3
player2: 2


[4, 7, 5, 8, 9, 6]


array([[4, 7, 5],
       [0, 0, 0]])

In [66]:
for i in range(4):
    print(c[i])

[ 4  2  9  0  0 11  5  8  6  9  7  2  5]
[11  1  4  1  1 10 12  8  2  1  5  0  7]
[12  7  3 10  6 12  8 11  9  7  8  9  5]
[10  3 11 10  6  2  0 12  4  4  3  6  3]


In [67]:
list(range(0,13))


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [68]:
b // 13

array([[3, 3, 1, 3, 1, 3, 1, 2, 3, 2, 3, 0, 2],
       [2, 2, 0, 0, 1, 1, 2, 0, 2, 3, 0, 4, 2],
       [1, 1, 2, 2, 0, 0, 1, 1, 0, 0, 3, 3, 3],
       [3, 0, 0, 0, 1, 1, 2, 3, 1, 2, 3, 2, 1]])

In [69]:
def analysis_cards_rank():
    '''
    find ranks numbers.
    鐵支, 三條, 對子.
    '''
    ranks       = b % 13
    ranks_index = []

    for i in range(4):

        ranks_index.append([])
        for j in range(0, 13):
            ranks_index[i].append(j)
            ranks_index[i].append(list(ranks[i]).count(j))
    return ranks_index

def analysis_cards_suits():
    '''
    找出花色
    同花順, 同花.
    '''
    suits       = b // 13
    suits_index = []

    for i in range(4):
        suits_index.append([])
        # [1, 2, 3, 4] = ['♠', '♦', '♥', '♣']
        for j in range(1, 5):
            suits_index[i].append(j)
            suits_index[i].append(list(suits[i]).count(j))
    return suits_index

In [70]:
np.array(analysis_cards_rank())

array([[ 0,  2,  1,  0,  2,  2,  3,  0,  4,  1,  5,  2,  6,  1,  7,  1,
         8,  1,  9,  2, 10,  0, 11,  1, 12,  0],
       [ 0,  1,  1,  4,  2,  1,  3,  0,  4,  1,  5,  1,  6,  0,  7,  1,
         8,  1,  9,  0, 10,  1, 11,  1, 12,  1],
       [ 0,  0,  1,  0,  2,  0,  3,  1,  4,  0,  5,  1,  6,  1,  7,  2,
         8,  2,  9,  2, 10,  1, 11,  1, 12,  2],
       [ 0,  1,  1,  0,  2,  1,  3,  3,  4,  2,  5,  0,  6,  2,  7,  0,
         8,  0,  9,  0, 10,  2, 11,  1, 12,  1]])

In [71]:
np.array(analysis_cards_suits())

array([[1, 3, 2, 3, 3, 6, 4, 0],
       [1, 2, 2, 5, 3, 1, 4, 1],
       [1, 4, 2, 2, 3, 3, 4, 0],
       [1, 4, 2, 3, 3, 3, 4, 0]])

In [39]:
DD = []
DD.append([])
DD[0].append(5)

DD.append([])
DD[1].append(5)

In [40]:
DD

[[5], [5]]

In [43]:
for i in range(1,8,2):
    print(i)

1
3
5
7
